# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testresults", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="source_file",
            field=models.CharField(default="test_results.json", max_length=255),
            preserve_default=False,
        )
    ]
