# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0003_auto_20170814_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='robot_xml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
