# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0003_auto_20170814_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmethod',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='testmethod',
            name='test_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
