# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testresults", "0004_testresult_robot_xml")]

    operations = [
        migrations.AddField(
            model_name="testclass",
            name="test_type",
            field=models.CharField(
                choices=[
                    (b"Apex", b"Apex"),
                    (b"Robot", b"Robot"),
                    (b"Other", b"Other"),
                ],
                db_index=True,
                default="Apex",
                max_length=32,
            ),
            preserve_default=False,
        )
    ]
