# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 14:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testresults", "0005_testclass_test_type")]

    operations = [
        migrations.CreateModel(
            name="TestResultAsset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.FileField(upload_to=b"")),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="testresults.TestResult",
                    ),
                ),
            ],
        )
    ]
