# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0007_auto_20180824_2100"),
        ("testresults", "0004_auto_20180723_2213"),
    ]

    operations = []
