# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0009_auto_20181207_2010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="callouts_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="callouts_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="callouts_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="cpu_time_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="cpu_time_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="cpu_time_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_rows_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_rows_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_rows_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_statements_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_statements_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="dml_statements_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="future_calls_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="future_calls_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="future_calls_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="heap_size_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="heap_size_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="heap_size_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="mobile_apex_push_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="mobile_apex_push_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="mobile_apex_push_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="query_rows_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="query_rows_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="query_rows_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="queueable_jobs_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="queueable_jobs_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="queueable_jobs_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="soql_queries_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="soql_queries_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="soql_queries_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="sosl_queries_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="sosl_queries_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="sosl_queries_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_callouts_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_callouts_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_callouts_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_cpu_time_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_cpu_time_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_cpu_time_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_rows_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_rows_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_rows_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_statements_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_statements_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_dml_statements_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_email_invocations_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_email_invocations_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_email_invocations_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_future_calls_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_future_calls_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_future_calls_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_heap_size_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_heap_size_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_heap_size_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_mobile_apex_push_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_mobile_apex_push_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_mobile_apex_push_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_query_rows_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_query_rows_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_query_rows_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_queueable_jobs_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_queueable_jobs_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_queueable_jobs_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_soql_queries_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_soql_queries_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_soql_queries_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_sosl_queries_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_sosl_queries_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_sosl_queries_used",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
