# Generated by Django 2.1.7 on 2019-04-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0006_remove_repository_public"),
        ("plan", "0026_auto_20190209_0101"),
        ("testresults", "0010_auto_20190204_1732"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResultPerfWeeklySummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agg_duration_average", models.FloatField(null=True)),
                ("agg_duration_slow", models.FloatField(null=True)),
                ("agg_duration_fast", models.FloatField(null=True)),
                ("agg_cpu_usage_average", models.FloatField(null=True)),
                ("agg_cpu_usage_low", models.FloatField(null=True)),
                ("agg_cpu_usage_high", models.FloatField(null=True)),
                ("agg_count", models.IntegerField()),
                ("agg_failures", models.IntegerField()),
                ("agg_assertion_failures", models.IntegerField()),
                ("agg_DML_failures", models.IntegerField()),
                ("agg_other_failures", models.IntegerField()),
                ("week_start", models.DateField()),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="testresults.TestMethod",
                    ),
                ),
                (
                    "rel_branch",
                    models.ForeignKey(
                        db_column="branch_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repository.Branch",
                    ),
                ),
                (
                    "rel_plan",
                    models.ForeignKey(
                        db_column="plan_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plan.Plan",
                    ),
                ),
                (
                    "rel_planrepo",
                    models.ForeignKey(
                        db_column="planrepo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plan.PlanRepository",
                    ),
                ),
                (
                    "rel_repo",
                    models.ForeignKey(
                        db_column="repo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repository.Repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Results Weekly Performance Summary",
                "verbose_name_plural": "Test Results Weekly Performance Summaries",
                "db_table": "testresult_weekly_perfsummary",
            },
        ),
        migrations.AddIndex(
            model_name="testresultperfweeklysummary",
            index=models.Index(
                fields=["rel_repo", "rel_branch", "rel_plan", "method", "week_start"],
                name="testresult_weekly_lookup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testresultperfweeklysummary",
            unique_together={
                ("rel_repo", "rel_branch", "rel_plan", "method", "week_start")
            },
        ),
    ]
