# Generated by Django 2.1.7 on 2019-04-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0026_auto_20190209_0101"),
        ("repository", "0006_remove_repository_public"),
        ("testresults", "0010_auto_20190204_1732"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResultPerfSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow", models.CharField(max_length=255)),
                ("day", models.DateField()),
                ("duration_average", models.FloatField()),
                ("count", models.IntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="testresult_perfsummaries",
                        to="repository.Branch",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="testresult_perfsummaries",
                        to="testresults.TestMethod",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="testresult_perfsummaries",
                        to="plan.Plan",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="testresult_perfsummaries",
                        to="repository.Repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Results Performance Summary",
                "verbose_name_plural": "Test Results Performance Summaries",
                "db_table": "testresult_perfsummary",
            },
        ),
        migrations.AlterUniqueTogether(
            name="testresultperfsummary",
            unique_together={("repo", "branch", "flow", "plan", "method", "day")},
        ),
    ]
