# Generated by Django 2.1.7 on 2019-04-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testresults", "0011_auto_20190402_0029")]

    operations = [
        migrations.AddField(
            model_name="testresultperfsummary",
            name="cpu_usage_average",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="cpu_usage_high",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="cpu_usage_low",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="duration_fast",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="duration_slow",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="failures",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testresultperfsummary",
            name="duration_average",
            field=models.FloatField(null=True),
        ),
    ]
