# Generated by Django 2.1.7 on 2019-04-26 17:55

from django.db import migrations, models
from scheduler.models import RepeatableJob
from django.utils import timezone
from django_rq import job


@job("short")
def install_generate_summaries_job(apps, schema_editor):
    job, created = RepeatableJob.objects.get_or_create(
        callable="metaci.testresults.tasks.generate_summaries",
        enabled=True,
        name="generate_summaries_job",
        queue="short",
        defaults={
            "interval": 30,
            "interval_unit": "minutes",
            "scheduled_time": timezone.now(),
        },
    )


def uninstall_generate_summaries_job(apps, schema_editor):
    RepeatableJob.objects.filter(name="generate_summaries_job").delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("testresults", "0012_create_summaries")]

    operations = [
        migrations.RunPython(
            install_generate_summaries_job,
            reverse_code=uninstall_generate_summaries_job,
        )
    ]
