# Generated by Django 2.1.7 on 2019-04-26 17:55

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("testresults", "0012_create_summaries")]

    operations = []
