# Generated by Django 2.2.7 on 2019-11-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("build", "0033_build_org_api_version"),
        ("testresults", "0013_install_summary_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="robot_task",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Task which generated the original output.xml file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_results",
                to="build.FlowTask",
            ),
        ),
    ]
