# Generated by Django 2.1.7 on 2019-04-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0006_remove_repository_public"),
        ("plan", "0026_auto_20190209_0101"),
        ("testresults", "0013_auto_20190402_1401"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="testresultperfsummary", name="lookup"),
        migrations.AlterUniqueTogether(
            name="testresultperfsummary",
            unique_together={("repo", "branch", "plan", "method", "day")},
        ),
        migrations.AddIndex(
            model_name="testresultperfsummary",
            index=models.Index(
                fields=["repo", "branch", "plan", "method", "day"], name="lookup"
            ),
        ),
        migrations.RemoveField(model_name="testresultperfsummary", name="flow"),
    ]
