# Generated by Django 2.2.7 on 2019-12-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0014_testresult_robot_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testresult", old_name="robot_task", new_name="task",
        ),
    ]
