# Generated by Django 2.1.7 on 2019-04-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("testresults", "0014_auto_20190416_2217")]

    operations = [
        migrations.RenameField(
            model_name="testresultperfsummary", old_name="count", new_name="agg_count"
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="cpu_usage_average",
            new_name="agg_cpu_usage_average",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="cpu_usage_high",
            new_name="agg_cpu_usage_high",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="cpu_usage_low",
            new_name="agg_cpu_usage_low",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="duration_average",
            new_name="agg_duration_average",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="duration_fast",
            new_name="agg_duration_fast",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="duration_slow",
            new_name="agg_duration_slow",
        ),
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="failures",
            new_name="agg_failures",
        ),
    ]
