# Generated by Django 2.1.7 on 2019-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testresults", "0015_auto_20190417_1403")]

    operations = [
        migrations.AddField(
            model_name="testresultperfsummary",
            name="agg_DML_failures",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="agg_Other_failures",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="agg_assertion_failures",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresultperfsummary",
            name="agg_success_percentage",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
