# Generated by Django 2.2.11 on 2020-05-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0015_auto_20191202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultperfweeklysummary',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testresults.TestMethod'),
        ),
        migrations.AlterField(
            model_name='testresultperfweeklysummary',
            name='rel_branch',
            field=models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='repository.Branch'),
        ),
        migrations.AlterField(
            model_name='testresultperfweeklysummary',
            name='rel_plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='plan.Plan'),
        ),
        migrations.AlterField(
            model_name='testresultperfweeklysummary',
            name='rel_planrepo',
            field=models.ForeignKey(db_column='planrepo_id', on_delete=django.db.models.deletion.CASCADE, to='plan.PlanRepository'),
        ),
        migrations.AlterField(
            model_name='testresultperfweeklysummary',
            name='rel_repo',
            field=models.ForeignKey(db_column='repo_id', on_delete=django.db.models.deletion.CASCADE, to='repository.Repository'),
        ),
    ]
