# Generated by Django 2.2.13 on 2020-07-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0016_auto_20200505_1940"),
        ("testresults", "0016_testresult_robot_keyword"),
    ]

    operations = []
