# Generated by Django 2.1.7 on 2019-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("testresults", "0016_auto_20190417_1638")]

    operations = [
        migrations.RemoveField(
            model_name="testresultperfsummary", name="agg_success_percentage"
        )
    ]
