# Generated by Django 2.1.7 on 2019-04-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0017_remove_testresultperfsummary_agg_success_percentage")
    ]

    operations = [
        migrations.RenameField(
            model_name="testresultperfsummary",
            old_name="agg_Other_failures",
            new_name="agg_other_failures",
        )
    ]
