# Generated by Django 2.2.16 on 2020-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0018_testresult_robot_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="email_invocations_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="email_invocations_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="email_invocations_used",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="worst_limit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="worst_limit_nontest",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="worst_limit_nontest_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="worst_limit_test",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="worst_limit_test_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
