# Generated by Django 3.1.7 on 2021-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0019_auto_20201016_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="robot_tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
