# Generated by Django 2.1.7 on 2019-04-25 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0026_auto_20190209_0101"),
        ("repository", "0006_remove_repository_public"),
        ("testresults", "0019_auto_20190423_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresultperfsummary",
            name="rel_planrepo",
            field=models.ForeignKey(
                db_column="planrepo_id",
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                to="plan.PlanRepository",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testresultperfweeklysummary",
            name="rel_planrepo",
            field=models.ForeignKey(
                db_column="planrepo_id",
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                to="plan.PlanRepository",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testresultperfsummary",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="testresults.TestMethod"
            ),
        ),
    ]
