# Generated by Django 3.1.13 on 2021-12-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testresults", "0020_auto_20210405_1622"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestResultPerfWeeklySummary",
        ),
    ]
