# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 21:49
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("repository", "0004_remove_branch_deleted")]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("draft", "draft"), ("published", "published")],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="version name",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="version number",
                    ),
                ),
                (
                    "package_version_id",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        verbose_name="package version id",
                    ),
                ),
                (
                    "git_tag",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="git tag"
                    ),
                ),
                (
                    "github_release",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="github release",
                    ),
                ),
                (
                    "trialforce_id",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        verbose_name="trialforce template id",
                    ),
                ),
                (
                    "release_creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="release creation date"
                    ),
                ),
                (
                    "sandbox_push_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="sandbox push date"
                    ),
                ),
                (
                    "production_push_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="production push date"
                    ),
                ),
                (
                    "created_from_commit",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="created from commit",
                    ),
                ),
                (
                    "work_item_link",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="work item link",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="repository.Repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "release",
                "get_latest_by": "production_push_date",
                "verbose_name_plural": "releases",
                "ordering": ["-production_push_date"],
            },
        )
    ]
