# Generated by Django 2.2.12 on 2020-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0003_populate_releases"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="change_case_link",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="change case link"
            ),
        ),
    ]
