# Generated by Django 2.2.12 on 2020-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0004_auto_20200513_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="git_tag",
            field=models.CharField(max_length=1024, null=True, verbose_name="git tag"),
        ),
    ]
