# Generated by Django 2.2.14 on 2020-08-12 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0005_auto_20200513_2125"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeCaseTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "case_template_id",
                    models.CharField(max_length=18, verbose_name="case template id"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="release",
            name="change_case_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="release.ChangeCaseTemplate",
            ),
        ),
    ]
