# Generated by Django 2.2.16 on 2020-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0007_auto_20201116_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="production_push_date",
            field=models.DateField(
                default="2020-11-22", verbose_name="production push date"
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="release_creation_date",
            field=models.DateField(
                default="2020-11-16", verbose_name="release creation date"
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sandbox_push_date",
            field=models.DateField(
                default="2020-11-22", verbose_name="sandbox push date"
            ),
        ),
    ]
