# Generated by Django 2.2.16 on 2020-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0008_auto_20201116_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="production_push_date",
            field=models.DateField(
                blank=True,
                default="2020-11-25",
                null=True,
                verbose_name="production push date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="release_creation_date",
            field=models.DateField(
                blank=True,
                default="2020-11-19",
                null=True,
                verbose_name="release creation date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sandbox_push_date",
            field=models.DateField(
                blank=True,
                default="2020-11-19",
                null=True,
                verbose_name="sandbox push date",
            ),
        ),
    ]
