# Generated by Django 2.2.16 on 2020-11-20 21:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0009_auto_20201119_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="production_push_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2020, 11, 26),
                null=True,
                verbose_name="production push date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="release_creation_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2020, 11, 20),
                null=True,
                verbose_name="release creation date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sandbox_push_date",
            field=models.DateField(
                blank=True,
                default=datetime.date(2020, 11, 20),
                null=True,
                verbose_name="sandbox push date",
            ),
        ),
    ]
