# Generated by Django 2.2.16 on 2020-11-20 21:24

from django.db import migrations, models

import metaci.release.models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0010_auto_20201120_2109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="production_push_date",
            field=models.DateField(
                blank=True,
                default=metaci.release.models.Release.get_production_date,
                null=True,
                verbose_name="production push date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="release_creation_date",
            field=models.DateField(
                blank=True,
                default=metaci.release.models.Release.get_sandbox_date,
                null=True,
                verbose_name="release creation date",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="sandbox_push_date",
            field=models.DateField(
                blank=True,
                default=metaci.release.models.Release.get_sandbox_date,
                null=True,
                verbose_name="sandbox push date",
            ),
        ),
    ]
