# Generated by Django 3.0.3 on 2021-02-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0035_auto_20201016_1935"),
        ("release", "0012_release_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementationStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="start_time"
                    ),
                ),
                (
                    "stop_time",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="stop_time"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="plan.Plan",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="release.Release",
                    ),
                ),
            ],
        ),
    ]
