# Generated by Django 3.1.7 on 2021-04-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0013_implementationstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="change_case_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="release.changecasetemplate",
            ),
        ),
    ]
