# Generated by Django 3.0.3 on 2021-02-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0013_implementationstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementationstep",
            name="implementation_step_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="implementation step",
            ),
        ),
    ]
