# Generated by Django 3.1.7 on 2021-04-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0014_auto_20210406_0241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="change_case_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="release.changecasetemplate",
                null=False,
                blank=False,
            ),
        ),
    ]
