# Generated by Django 3.0.3 on 2021-02-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0014_implementationstep_implementation_step_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="i",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releases",
                to="release.ImplementationStep",
            ),
        ),
    ]
