# Generated by Django 3.0.3 on 2021-02-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0015_release_i"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="i",
            new_name="sandbox_implemention_step",
        ),
    ]
