# Generated by Django 3.1.10 on 2021-05-19 22:47

from django.db import migrations, models


def populate_version_number(apps, schema_editor):
    Release = apps.get_model("release.Release")
    Release.objects.filter(version_number__isnull=True).update(version_number="N/A")


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0015_auto_20210407_0218"),
    ]

    operations = [
        migrations.RunPython(populate_version_number, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="release",
            name="version_number",
            field=models.CharField(max_length=255, verbose_name="version number"),
        ),
    ]
