# Generated by Django 3.1.10 on 2021-05-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0015_auto_20210407_0218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="change_case_link",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="change case ID"
            ),
        ),
    ]
