# Generated by Django 3.1.13 on 2021-09-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0018_push_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseCohort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Active", "Active"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Planned",
                        max_length=9,
                    ),
                ),
                (
                    "merge_freeze_start",
                    models.DateTimeField(verbose_name="Merge Freeze Start Time"),
                ),
                (
                    "merge_freeze_end",
                    models.DateTimeField(verbose_name="Merge Freeze End Time"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="release",
            name="release_cohort",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="release.releasecohort",
            ),
        ),
    ]
