# Generated by Django 3.1.13 on 2021-09-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0019_release_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="release_cohort",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="releases",
                to="release.releasecohort",
            ),
        ),
    ]
