# Generated by Django 3.1.13 on 2021-09-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0020_auto_20210920_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecohort',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Planned', max_length=9),
        ),
    ]
