# Generated by Django 3.1.13 on 2021-11-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0022_auto_20211110_2127"),
        ("release", "0022_auto_20211110_2221"),
    ]

    operations = []
