# Generated by Django 3.1.13 on 2021-11-11 17:34

from django.db import migrations, models


def migrate_release_cohort_choices(apps, schema_editor):
    ReleaseCohort = apps.get_model("release.ReleaseCohort")

    for rc in ReleaseCohort.objects.all():
        rc.status = rc.status.lower()
        rc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0023_merge_20211110_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasecohort",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="planned",
                max_length=9,
            ),
        ),
        migrations.RunPython(migrate_release_cohort_choices),
    ]
