# Generated by Django 3.1.13 on 2021-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0023_merge_20211110_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasecohort",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="planned",
                max_length=9,
            ),
        ),
    ]
