# Generated by Django 3.1.13 on 2021-11-17 01:26

from django.db import migrations


def migrate_release_choices(apps, schema_editor):
    Release = apps.get_model("release.Release")

    for r in Release.objects.filter(status__in=["published", "hidden"]):
        r.status = "completed"
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ("release", "0024_auto_20211111_1734"),
    ]

    operations = [
        migrations.RunPython(migrate_release_choices),
    ]
