# Generated by Django 3.1.13 on 2021-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0025_auto_20211117_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecohort',
            name='dependency_graph',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasecohort',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
