# Generated by Django 3.1.14 on 2022-01-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0026_auto_20211123_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecohort',
            name='metapush_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasecohort',
            name='metapush_push_cohort_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='releasecohort',
            name='metapush_push_schedule_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='releasecohort',
            name='send_to_metapush',
            field=models.BooleanField(default=True),
        ),
    ]
