# Generated by Django 3.1.14 on 2022-02-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0027_auto_20220131_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasecohort',
            old_name='send_to_metapush',
            new_name='enable_metapush',
        ),
    ]
