// flow-typed signature: 85714de988e653420833749928b22e55
// flow-typed version: <<STUB>>/@salesforce/design-system-react_v0.9.6/flow_v0.93.0
// @flow

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@salesforce/design-system-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@salesforce/design-system-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@salesforce/design-system-react/components/input' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/button' {
  declare module.exports: any;
}

declare module '@salesforce/design-system-react/components/tooltip' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/spinner' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/data-table' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/settings' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/icon-settings' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/accordion' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/accordion/panel' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/brand-band' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/data-table/column' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/combobox' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/combobox/filter' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/icon' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/date-picker' {
  declare module.exports: any;
}
declare module '@salesforce/design-system-react/components/illustration' {
  declare module.exports: any;
}
