// flow-typed signature: 0c5a97a4f4ef0dd70e86cff61ca47096
// flow-typed version: <<STUB>>/@salesforce/lwc-jest_v^0.5.4/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@salesforce/lwc-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@salesforce/lwc-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@salesforce/lwc-jest/config' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/config' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/accordion/accordion' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/accordionSection/accordionSection' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/avatar/avatar' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/badge/badge' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/breadcrumb/breadcrumb' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/breadcrumbs/breadcrumbs' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/button/button' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonGroup/buttonGroup' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonIcon/buttonIcon' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonIconStateful/buttonIconStateful' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonMenu/buttonMenu' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonStateful/buttonStateful' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/card/card' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/carousel/carousel' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/carouselImage/carouselImage' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/checkboxGroup/checkboxGroup' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/clickToDial/clickToDial' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/combobox/combobox' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/configProvider/configProvider' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/datatable/datatable' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/dualListbox/dualListbox' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/dynamicIcon/dynamicIcon' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/fileUpload/fileUpload' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedAddress/formattedAddress' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedDateTime/formattedDateTime' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedEmail/formattedEmail' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedLocation/formattedLocation' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedName/formattedName' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedNumber/formattedNumber' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedPhone/formattedPhone' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedRichText/formattedRichText' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedText/formattedText' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedTime/formattedTime' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedUrl/formattedUrl' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/formElement/formElement' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/helptext/helptext' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/icon/icon' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/input/input' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/inputAddress/inputAddress' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/inputField/inputField' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/inputLocation/inputLocation' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/inputName/inputName' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/inputRichText/inputRichText' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/layout/layout' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/layoutItem/layoutItem' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/map/map' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/menuDivider/menuDivider' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/menuItem/menuItem' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/menuSubheader/menuSubheader' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/messages/messages' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/navigation/navigation' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/notificationsLibrary/notificationsLibrary' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/outputField/outputField' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/overlayLibrary/overlayLibrary' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/pill/pill' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/pillContainer/pillContainer' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/platformResourceLoader/platformResourceLoader' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/platformShowToastEvent/platformShowToastEvent' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/progressBar/progressBar' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/progressIndicator/progressIndicator' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/progressStep/progressStep' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/radioGroup/radioGroup' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/recordEditForm/recordEditForm' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/recordForm/recordForm' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/recordViewForm/recordViewForm' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/relativeDateTime/relativeDateTime' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/slider/slider' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/spinner/spinner' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/tab/tab' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/tabset/tabset' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/textarea/textarea' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/tile/tile' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/tree/tree' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/treeGrid/treeGrid' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/uiActionsApi/uiActionsApi' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/uiListApi/uiListApi' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/uiLookupsApi/uiLookupsApi' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/uiObjectInfoApi/uiObjectInfoApi' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/uiRecordApi/uiRecordApi' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigation/verticalNavigation' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItem/verticalNavigationItem' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemBadge/verticalNavigationItemBadge' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemIcon/verticalNavigationItemIcon' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationOverflow/verticalNavigationOverflow' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationSection/verticalNavigationSection' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/log' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/options/options' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/resolver' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/__mocks__/project' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/jest' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/module' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/project' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/shell' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/test-runner' {
  declare module.exports: any;
}

declare module '@salesforce/lwc-jest/src/utils/yargs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@salesforce/lwc-jest/config.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/config'>;
}
declare module '@salesforce/lwc-jest/src/config.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/config'>;
}
declare module '@salesforce/lwc-jest/src/index' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src'>;
}
declare module '@salesforce/lwc-jest/src/index.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/accordion/accordion.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/accordion/accordion'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/accordionSection/accordionSection.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/accordionSection/accordionSection'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/avatar/avatar.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/avatar/avatar'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/badge/badge.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/badge/badge'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/breadcrumb/breadcrumb.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/breadcrumb/breadcrumb'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/breadcrumbs/breadcrumbs.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/breadcrumbs/breadcrumbs'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/button/button.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/button/button'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonGroup/buttonGroup.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/buttonGroup/buttonGroup'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonIcon/buttonIcon.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/buttonIcon/buttonIcon'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonIconStateful/buttonIconStateful.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/buttonIconStateful/buttonIconStateful'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonMenu/buttonMenu.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/buttonMenu/buttonMenu'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/buttonStateful/buttonStateful.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/buttonStateful/buttonStateful'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/card/card.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/card/card'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/carousel/carousel.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/carousel/carousel'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/carouselImage/carouselImage.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/carouselImage/carouselImage'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/checkboxGroup/checkboxGroup.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/checkboxGroup/checkboxGroup'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/clickToDial/clickToDial.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/clickToDial/clickToDial'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/combobox/combobox.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/combobox/combobox'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/configProvider/configProvider.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/configProvider/configProvider'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/datatable/datatable.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/datatable/datatable'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/datatableKeyboardMixins/datatableKeyboardMixins'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/dualListbox/dualListbox.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/dualListbox/dualListbox'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/dynamicIcon/dynamicIcon.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/dynamicIcon/dynamicIcon'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/fileUpload/fileUpload.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/fileUpload/fileUpload'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedAddress/formattedAddress.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedAddress/formattedAddress'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedDateTime/formattedDateTime.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedDateTime/formattedDateTime'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedEmail/formattedEmail.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedEmail/formattedEmail'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedLocation/formattedLocation.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedLocation/formattedLocation'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedName/formattedName.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedName/formattedName'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedNumber/formattedNumber.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedNumber/formattedNumber'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedPhone/formattedPhone.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedPhone/formattedPhone'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedRichText/formattedRichText.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedRichText/formattedRichText'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedText/formattedText.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedText/formattedText'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedTime/formattedTime.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedTime/formattedTime'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formattedUrl/formattedUrl.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formattedUrl/formattedUrl'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/formElement/formElement.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/formElement/formElement'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/helptext/helptext.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/helptext/helptext'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/icon/icon.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/icon/icon'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/input/input.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/input/input'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/inputAddress/inputAddress.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/inputAddress/inputAddress'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/inputField/inputField.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/inputField/inputField'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/inputLocation/inputLocation.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/inputLocation/inputLocation'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/inputName/inputName.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/inputName/inputName'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/inputRichText/inputRichText.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/inputRichText/inputRichText'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/layout/layout.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/layout/layout'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/layoutItem/layoutItem.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/layoutItem/layoutItem'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/map/map.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/map/map'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/menuDivider/menuDivider.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/menuDivider/menuDivider'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/menuItem/menuItem.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/menuItem/menuItem'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/menuSubheader/menuSubheader.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/menuSubheader/menuSubheader'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/messages/messages.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/messages/messages'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/navigation/navigation.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/navigation/navigation'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/notificationsLibrary/notificationsLibrary.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/notificationsLibrary/notificationsLibrary'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/outputField/outputField.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/outputField/outputField'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/overlayLibrary/overlayLibrary.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/overlayLibrary/overlayLibrary'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/pill/pill.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/pill/pill'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/pillContainer/pillContainer.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/pillContainer/pillContainer'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/platformResourceLoader/platformResourceLoader.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/platformResourceLoader/platformResourceLoader'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/platformShowToastEvent/platformShowToastEvent.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/platformShowToastEvent/platformShowToastEvent'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/progressBar/progressBar.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/progressBar/progressBar'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/progressIndicator/progressIndicator.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/progressIndicator/progressIndicator'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/progressStep/progressStep.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/progressStep/progressStep'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/radioGroup/radioGroup.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/radioGroup/radioGroup'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/recordEditForm/recordEditForm.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/recordEditForm/recordEditForm'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/recordForm/recordForm.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/recordForm/recordForm'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/recordViewForm/recordViewForm.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/recordViewForm/recordViewForm'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/relativeDateTime/relativeDateTime.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/relativeDateTime/relativeDateTime'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/slider/slider.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/slider/slider'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/spinner/spinner.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/spinner/spinner'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/tab/tab.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/tab/tab'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/tabset/tabset.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/tabset/tabset'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/textarea/textarea.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/textarea/textarea'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/tile/tile.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/tile/tile'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/tree/tree.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/tree/tree'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/treeGrid/treeGrid.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/treeGrid/treeGrid'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/uiActionsApi/uiActionsApi.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/uiActionsApi/uiActionsApi'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/uiListApi/uiListApi.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/uiListApi/uiListApi'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/uiLookupsApi/uiLookupsApi.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/uiLookupsApi/uiLookupsApi'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/uiObjectInfoApi/uiObjectInfoApi.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/uiObjectInfoApi/uiObjectInfoApi'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/uiRecordApi/uiRecordApi.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/uiRecordApi/uiRecordApi'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigation/verticalNavigation.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigation/verticalNavigation'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItem/verticalNavigationItem.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItem/verticalNavigationItem'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemBadge/verticalNavigationItemBadge.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemBadge/verticalNavigationItemBadge'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemIcon/verticalNavigationItemIcon.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationItemIcon/verticalNavigationItemIcon'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationOverflow/verticalNavigationOverflow.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationOverflow/verticalNavigationOverflow'>;
}
declare module '@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationSection/verticalNavigationSection.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/lightning-stubs/verticalNavigationSection/verticalNavigationSection'>;
}
declare module '@salesforce/lwc-jest/src/log.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/log'>;
}
declare module '@salesforce/lwc-jest/src/options/options.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/options/options'>;
}
declare module '@salesforce/lwc-jest/src/resolver.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/resolver'>;
}
declare module '@salesforce/lwc-jest/src/utils/__mocks__/project.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/__mocks__/project'>;
}
declare module '@salesforce/lwc-jest/src/utils/jest.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/jest'>;
}
declare module '@salesforce/lwc-jest/src/utils/module.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/module'>;
}
declare module '@salesforce/lwc-jest/src/utils/project.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/project'>;
}
declare module '@salesforce/lwc-jest/src/utils/shell.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/shell'>;
}
declare module '@salesforce/lwc-jest/src/utils/test-runner.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/test-runner'>;
}
declare module '@salesforce/lwc-jest/src/utils/yargs.js' {
  declare module.exports: $Exports<'@salesforce/lwc-jest/src/utils/yargs'>;
}
