# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0005_auto_20161213_1938'),
        ('testresults', '0002_auto_20161222_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='build',
        ),
        migrations.AddField(
            model_name='testresult',
            name='build_flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='build.BuildFlow'),
            preserve_default=False,
        ),
    ]
