# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0003_auto_20161222_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcodeunit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testcodeunit',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='testcodeunit',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='testcodeunit',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='testcodeunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testresults.TestCodeUnit'),
        ),
    ]
