# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('plan', '0002_plan_devhub'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly')], max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Branch')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
            ],
        ),
    ]
