// flow-typed signature: bb886ad706f4f0997c54f4657c6dd2cc
// flow-typed version: <<STUB>>/i18next-browser-languagedetector_v^3.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-browser-languagedetector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-browser-languagedetector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/cookie' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/htmlTag' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/localStorage' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/navigator' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/path' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/querystring' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/subdomain' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/cookie' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/htmlTag' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/localStorage' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/navigator' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/path' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/querystring' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/browserLookups/subdomain' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/index' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/es/utils' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min' {
  declare module.exports: any;
}

declare module 'i18next-browser-languagedetector/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/cookie.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/cookie'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/htmlTag.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/htmlTag'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/localStorage.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/localStorage'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/navigator.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/navigator'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/path.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/path'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/querystring.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/querystring'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/browserLookups/subdomain.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/browserLookups/subdomain'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/index.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/index'>;
}
declare module 'i18next-browser-languagedetector/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/commonjs/utils'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/cookie.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/cookie'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/htmlTag.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/htmlTag'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/localStorage.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/localStorage'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/navigator.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/navigator'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/path.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/path'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/querystring.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/querystring'>;
}
declare module 'i18next-browser-languagedetector/dist/es/browserLookups/subdomain.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/browserLookups/subdomain'>;
}
declare module 'i18next-browser-languagedetector/dist/es/index.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/index'>;
}
declare module 'i18next-browser-languagedetector/dist/es/utils.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/es/utils'>;
}
declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min'>;
}
declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/i18nextBrowserLanguageDetector'>;
}
declare module 'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/i18nextBrowserLanguageDetector.min'>;
}
declare module 'i18next-browser-languagedetector/index' {
  declare module.exports: $Exports<'i18next-browser-languagedetector'>;
}
declare module 'i18next-browser-languagedetector/index.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector'>;
}
declare module 'i18next-browser-languagedetector/rollup.config.js' {
  declare module.exports: $Exports<'i18next-browser-languagedetector/rollup.config'>;
}
