// flow-typed signature: 3cb2b9eadfcb97c96b3c6e42c72f9e2d
// flow-typed version: <<STUB>>/i18next-xhr-backend_v^2.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-xhr-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-xhr-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-xhr-backend/dist/commonjs/ajax' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/es/ajax' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/es/index' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/es/utils' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/i18nextXHRBackend.min' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-xhr-backend/dist/commonjs/ajax.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/commonjs/ajax'>;
}
declare module 'i18next-xhr-backend/dist/commonjs/index.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/commonjs/index'>;
}
declare module 'i18next-xhr-backend/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/commonjs/utils'>;
}
declare module 'i18next-xhr-backend/dist/es/ajax.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/es/ajax'>;
}
declare module 'i18next-xhr-backend/dist/es/index.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/es/index'>;
}
declare module 'i18next-xhr-backend/dist/es/utils.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/es/utils'>;
}
declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/umd/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min'>;
}
declare module 'i18next-xhr-backend/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/i18nextXHRBackend.min.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/i18nextXHRBackend.min'>;
}
declare module 'i18next-xhr-backend/index' {
  declare module.exports: $Exports<'i18next-xhr-backend'>;
}
declare module 'i18next-xhr-backend/index.js' {
  declare module.exports: $Exports<'i18next-xhr-backend'>;
}
declare module 'i18next-xhr-backend/rollup.config.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/rollup.config'>;
}
