// flow-typed signature: 4d241e0bd8c14d4cd13aa44d3878de1e
// flow-typed version: <<STUB>>/i18next-xhr-backend_v^3.2.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-xhr-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-xhr-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-xhr-backend/dist/cjs/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/esm/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/i18nextXHRBackend' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/i18nextXHRBackend.min' {
  declare module.exports: any;
}

declare module 'i18next-xhr-backend/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-xhr-backend/dist/cjs/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/cjs/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/dist/esm/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/esm/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/umd/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/dist/umd/i18nextXHRBackend.min'>;
}
declare module 'i18next-xhr-backend/i18nextXHRBackend.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/i18nextXHRBackend'>;
}
declare module 'i18next-xhr-backend/i18nextXHRBackend.min.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/i18nextXHRBackend.min'>;
}
declare module 'i18next-xhr-backend/index' {
  declare module.exports: $Exports<'i18next-xhr-backend'>;
}
declare module 'i18next-xhr-backend/index.js' {
  declare module.exports: $Exports<'i18next-xhr-backend'>;
}
declare module 'i18next-xhr-backend/rollup.config.js' {
  declare module.exports: $Exports<'i18next-xhr-backend/rollup.config'>;
}
