// flow-typed signature: df2194183bb82578649674a796214e82
// flow-typed version: <<STUB>>/sarcastic_v^1.5.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sarcastic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sarcastic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sarcastic/index' {
  declare module.exports: $Exports<'sarcastic'>;
}
declare module 'sarcastic/index.js' {
  declare module.exports: $Exports<'sarcastic'>;
}
