# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_repository_github_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['repo__name', 'repo__owner', 'name']},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name', 'owner']},
        ),
    ]
