# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("repository", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "ordering": ["repo__name", "repo__owner", "name"],
                "verbose_name_plural": "branches",
            },
        ),
        migrations.AlterModelOptions(
            name="repository",
            options={
                "ordering": ["name", "owner"],
                "verbose_name_plural": "repositories",
            },
        ),
    ]
