# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("repository", "0002_auto_20171031_2037")]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_removed",
            field=models.BooleanField(default=False),
        )
    ]
