# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20171031_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projectimages/'),
        ),
    ]
