# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('repository', '0003_repository_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
