# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("repository", "0004_remove_branch_deleted")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="release_tag_regex",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
