# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-02 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_repository_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='group',
        ),
    ]
