# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("repository", "0005_repository_release_tag_regex")]

    operations = [migrations.RemoveField(model_name="repository", name="public")]
