# Generated by Django 2.2.6 on 2019-10-25 14:53

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("repository", "0006_remove_repository_public")]

    operations = [
        migrations.AlterModelManagers(
            name="branch",
            managers=[("include_deleted", django.db.models.manager.Manager())],
        )
    ]
