# Generated by Django 2.2.12 on 2020-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20191025_1453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
            ],
        ),
    ]
