# Generated by Django 3.1.13 on 2021-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0008_auto_20200513_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="default_implementation_steps",
            field=models.JSONField(default=[], null=True),
        ),
    ]
