# Generated by Django 3.1.13 on 2021-07-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0009_default_implementation_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="default_implementation_steps",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
