# Generated by Django 3.1.13 on 2021-08-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0010_implementation_list_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
