# Generated by Django 3.1.14 on 2022-01-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0011_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="metapush_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
