# Generated by Django 3.1.14 on 2022-02-24 16:43
from django.db import migrations

def make_release_managers_group(apps, schema_editor):
    # Get perms we want for the group
    Permission = apps.get_model("auth", "Permission")
    permissions = [
        Permission.objects.get(name="Can add release cohort"),
        Permission.objects.get(name="Can change release cohort"),
        Permission.objects.get(name="Can add release"),
        Permission.objects.get(name="Can change release"),
    ]

    # Create release managers group with desired perms
    Group = apps.get_model('auth', 'Group')
    g = Group.objects.create(name="Release Managers")
    [g.permissions.add(perm) for perm in permissions]



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_github_socialapp'),
        # To work with Group and Permission models,
        # we depend on the last migration from the app
        # where the models reside.
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(make_release_managers_group)
    ]