from django.test import TestCase

# Create your tests here.

RELEASE_TAG_EVENT = """
Request URL: https://mrbelvedereci.herokuapp.com/webhook/github/push
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/fa15ca8
X-GitHub-Delivery: b965ab50-a096-11e8-953c-9b1d5d8d5661
X-GitHub-Event: push
X-Hub-Signature: sha1=2ed3f7cb63085fcf375eadbdefcc82b1005e4a11

Body:
{
  "ref": "refs/tags/rel/3.137",
  "before": "0000000000000000000000000000000000000000",
  "after": "16ead700bbf27d81c9987fedf7bdd9811506259a",
  "created": true,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/SalesforceFoundation/Cumulus/compare/rel/3.137",
  "commits": [

  ],
  "head_commit": {
    "id": "2dafd17ec72d81ed62a1444aa19980a2c11b3398",
    "tree_id": "e3cd10ec907acf27edf274a58efba6b708f1cc92",
    "distinct": true,
    "message": "Merge pull request #3220 from SalesforceFoundation/feature/rollups__acct-soft-credits\n\nAccount Soft Credits: Object and Rollups integration",
    "timestamp": "2018-08-13T17:44:52-07:00",
    "url": "https://github.com/SalesforceFoundation/Cumulus/commit/2dafd17ec72d81ed62a1444aa19980a2c11b3398",
    "author": {
      "name": "Dina G",
      "email": "dgamboni@salesforce.com",
      "username": "dgamboni"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [
      "src/classes/CRLP_AccountSkew_AccSoftCredit_BATCH.cls",
      "src/classes/CRLP_AccountSkew_AccSoftCredit_BATCH.cls-meta.xml",
      "src/classes/CRLP_Account_AccSoftCredit_BATCH.cls",
      "src/classes/CRLP_Account_AccSoftCredit_BATCH.cls-meta.xml",
      "src/classes/CRLP_RollupAccSoftCredit_SVC.cls",
      "src/classes/CRLP_RollupAccSoftCredit_SVC.cls-meta.xml",
      "src/classes/CRLP_RollupAccSoftCredit_TEST.cls",
      "src/classes/CRLP_RollupAccSoftCredit_TEST.cls-meta.xml",
      "src/classes/OPP_AccountSoftCredit_TDTM.cls",
      "src/classes/OPP_AccountSoftCredit_TDTM.cls-meta.xml",
      "src/classes/OPP_CurrencySync_TEST.cls",
      "src/classes/OPP_CurrencySync_TEST.cls-meta.xml",
      "src/layouts/Account_Soft_Credit__c-Account Soft Credit Layout.layout",
      "src/objectTranslations/Account_Soft_Credit__c-de.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-en_US.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-es.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-fr.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-iw.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-ja.objectTranslation",
      "src/objectTranslations/Account_Soft_Credit__c-nl_NL.objectTranslation",
      "src/objects/Account_Soft_Credit__c.object",
      "src/triggers/TDTM_AccountSoftCredit.trigger",
      "src/triggers/TDTM_AccountSoftCredit.trigger-meta.xml"
    ],
    "removed": [

    ],
    "modified": [
      "ApexDocContent/Opportunity.htm",
      "ApexDocContent/Rollups2.html",
      "scripts/CRLP_TEST_VALIDATE_ROLLUPS.cls",
      "src/aura/CRLP_Rollup/CRLP_RollupHelper.js",
      "src/aura/CRLP_RollupsContainer/CRLP_RollupsContainer.cmp",
      "src/aura/CRLP_RollupsContainer/CRLP_RollupsContainerController.js",
      "src/classes/CMT_UnitTestData_TEST.cls",
      "src/classes/CRLP_Batch_Base.cls",
      "src/classes/CRLP_Batch_Base_NonSkew.cls",
      "src/classes/CRLP_Batch_Base_Skew.cls",
      "src/classes/CRLP_DefaultConfigBuilder_TEST.cls",
      "src/classes/CRLP_Query_SEL.cls",
      "src/classes/CRLP_RecalculateBTN_CTRL.cls",
      "src/classes/CRLP_RecalculateBTN_TEST.cls",
      "src/classes/CRLP_RollupAccount_TEST.cls",
      "src/classes/CRLP_RollupBatch_SVC.cls",
      "src/classes/CRLP_RollupCMT.cls",
      "src/classes/CRLP_RollupProcessingOptions.cls",
      "src/classes/CRLP_RollupProcessor_SVC.cls",
      "src/classes/CRLP_RollupQueueable.cls",
      "src/classes/CRLP_RollupScheduler_TEST.cls",
      "src/classes/CRLP_RollupSoftCredit_SVC.cls",
      "src/classes/CRLP_RollupUI_SVC.cls",
      "src/classes/CRLP_RollupUI_TEST.cls",
      "src/classes/CRLP_Rollup_SEL.cls",
      "src/classes/CRLP_Rollup_SVC.cls",
      "src/classes/CRLP_Rollup_TDTM.cls",
      "src/classes/CRLP_SkewDispatcher_BATCH.cls",
      "src/classes/CRLP_VRollupHandler.cls",
      "src/classes/PSC_Opportunity_TDTM.cls",
      "src/classes/STG_PanelOppBatch_CTRL.cls",
      "src/classes/TDTM_DefaultConfig.cls",
      "src/classes/UTIL_MasterSchedulableHelper.cls",
      "src/classes/UTIL_UnitTestData_TEST.cls",
      "src/labels/CustomLabels.labels",
      "src/package.xml"
    ]
  },
  "repository": {
    "id": 13108586,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMzEwODU4Ng==",
    "name": "Cumulus",
    "full_name": "SalesforceFoundation/Cumulus",
    "owner": {
      "name": "SalesforceFoundation",
      "email": "",
      "login": "SalesforceFoundation",
      "id": 972305,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjk3MjMwNQ==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/972305?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/SalesforceFoundation",
      "html_url": "https://github.com/SalesforceFoundation",
      "followers_url": "https://api.github.com/users/SalesforceFoundation/followers",
      "following_url": "https://api.github.com/users/SalesforceFoundation/following{/other_user}",
      "gists_url": "https://api.github.com/users/SalesforceFoundation/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/SalesforceFoundation/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SalesforceFoundation/subscriptions",
      "organizations_url": "https://api.github.com/users/SalesforceFoundation/orgs",
      "repos_url": "https://api.github.com/users/SalesforceFoundation/repos",
      "events_url": "https://api.github.com/users/SalesforceFoundation/events{/privacy}",
      "received_events_url": "https://api.github.com/users/SalesforceFoundation/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/SalesforceFoundation/Cumulus",
    "description": "The current version of the Salesforce.org Nonprofit Success Pack",
    "fork": false,
    "url": "https://github.com/SalesforceFoundation/Cumulus",
    "forks_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/forks",
    "keys_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/teams",
    "hooks_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/hooks",
    "issue_events_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/issues/events{/number}",
    "events_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/events",
    "assignees_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/assignees{/user}",
    "branches_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/branches{/branch}",
    "tags_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/tags",
    "blobs_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/languages",
    "stargazers_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/stargazers",
    "contributors_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/contributors",
    "subscribers_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/subscribers",
    "subscription_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/subscription",
    "commits_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/contents/{+path}",
    "compare_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/merges",
    "archive_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/downloads",
    "issues_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/issues{/number}",
    "pulls_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/labels{/name}",
    "releases_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/releases{/id}",
    "deployments_url": "https://api.github.com/repos/SalesforceFoundation/Cumulus/deployments",
    "created_at": 1380153409,
    "updated_at": "2018-08-14T18:13:46Z",
    "pushed_at": 1534342984,
    "git_url": "git://github.com/SalesforceFoundation/Cumulus.git",
    "ssh_url": "git@github.com:SalesforceFoundation/Cumulus.git",
    "clone_url": "https://github.com/SalesforceFoundation/Cumulus.git",
    "svn_url": "https://github.com/SalesforceFoundation/Cumulus",
    "homepage": "http://www.salesforce.org/nonprofit/nonprofit-success-pack/",
    "size": 92043,
    "stargazers_count": 245,
    "watchers_count": 245,
    "language": "Apex",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 202,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 315,
    "license": {
      "key": "bsd-3-clause",
      "name": "BSD 3-Clause \"New\" or \"Revised\" License",
      "spdx_id": "BSD-3-Clause",
      "url": "https://api.github.com/licenses/bsd-3-clause",
      "node_id": "MDc6TGljZW5zZTU="
    },
    "forks": 202,
    "open_issues": 315,
    "watchers": 245,
    "default_branch": "master",
    "stargazers": 245,
    "master_branch": "master",
    "organization": "SalesforceFoundation"
  },
  "pusher": {
    "name": "mrbelvedere",
    "email": "mrbelvedere@users.noreply.github.com"
  },
  "organization": {
    "login": "SalesforceFoundation",
    "id": 972305,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjk3MjMwNQ==",
    "url": "https://api.github.com/orgs/SalesforceFoundation",
    "repos_url": "https://api.github.com/orgs/SalesforceFoundation/repos",
    "events_url": "https://api.github.com/orgs/SalesforceFoundation/events",
    "hooks_url": "https://api.github.com/orgs/SalesforceFoundation/hooks",
    "issues_url": "https://api.github.com/orgs/SalesforceFoundation/issues",
    "members_url": "https://api.github.com/orgs/SalesforceFoundation/members{/member}",
    "public_members_url": "https://api.github.com/orgs/SalesforceFoundation/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/972305?v=4",
    "description": ""
  },
  "sender": {
    "login": "mrbelvedere",
    "id": 5545431,
    "node_id": "MDQ6VXNlcjU1NDU0MzE=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/5545431?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mrbelvedere",
    "html_url": "https://github.com/mrbelvedere",
    "followers_url": "https://api.github.com/users/mrbelvedere/followers",
    "following_url": "https://api.github.com/users/mrbelvedere/following{/other_user}",
    "gists_url": "https://api.github.com/users/mrbelvedere/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mrbelvedere/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mrbelvedere/subscriptions",
    "organizations_url": "https://api.github.com/users/mrbelvedere/orgs",
    "repos_url": "https://api.github.com/users/mrbelvedere/repos",
    "events_url": "https://api.github.com/users/mrbelvedere/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mrbelvedere/received_events",
    "type": "User",
    "site_admin": false
  }
}
"""