# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170111_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchnotification',
            name='on_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchnotification',
            name='on_fail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchnotification',
            name='on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannotification',
            name='on_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plannotification',
            name='on_fail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plannotification',
            name='on_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repositorynotification',
            name='on_error',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repositorynotification',
            name='on_fail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repositorynotification',
            name='on_success',
            field=models.BooleanField(default=False),
        ),
    ]
