# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-13 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_planrepositorynotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrepositorynotification',
            name='planrepository',
        ),
        migrations.RemoveField(
            model_name='planrepositorynotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlanRepositoryNotification',
        ),
    ]
