# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_planrepositorynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchnotification',
            name='follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plannotification',
            name='follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planrepositorynotification',
            name='follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repositorynotification',
            name='follow',
            field=models.BooleanField(default=True),
        ),
    ]
