# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_remove_branch_deleted'),
        ('plan', '0015_auto_20180314_2252'),
        ('notification', '0008_auto_20180603_2202'),
    ]

    operations = [

        migrations.AlterField(
            model_name='branchnotification',
            name='branch',
            field=models.ForeignKey(db_column='branch_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='repository.Branch'),
        ),
        migrations.AlterField(
            model_name='plannotification',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='plan.Plan'),
        ),
        migrations.AlterField(
            model_name='planrepositorynotification',
            name='planrepository',
            field=models.ForeignKey(db_column='planrepository_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='plan.PlanRepository'),
        ),
        migrations.AlterField(
            model_name='repositorynotification',
            name='repo',
            field=models.ForeignKey(db_column='repo_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='repository.Repository'),
        ),
        migrations.RenameField(
            model_name='branchnotification',
            old_name='branch',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='plannotification',
            old_name='plan',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='planrepositorynotification',
            old_name='planrepository',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='repositorynotification',
            old_name='repo',
            new_name='target',
        ),
    ]   
