# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='devhub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
