# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("plan", "0003_planschedule")]

    operations = [migrations.RemoveField(model_name="plan", name="devhub")]
