# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_plan_devhub'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='junit_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
