# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models

import metaci.plan.models


class Migration(migrations.Migration):

    dependencies = [("plan", "0007_plan_dashboard")]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="yaml_config",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[metaci.plan.models.validate_yaml_field],
            ),
        )
    ]
