# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('plan', '0008_plan_yaml_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='repo',
        ),
        migrations.AddField(
            model_name='plan',
            name='repositories',
            field=models.ManyToManyField(related_name='plans', to='repository.Repository'),
        ),
    ]
