# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 19:40
from __future__ import unicode_literals

from django.db import migrations


def copy_repo(apps, schema_editor):
    Plan = apps.get_model("plan", "Plan")
    PlanRepository = apps.get_model("plan", "PlanRepository")
    for plan in Plan.objects.all():
        PlanRepository.objects.create(plan=plan, repo=plan.repo)


class Migration(migrations.Migration):

    dependencies = [("plan", "0009_plan_repos_m2m")]

    operations = [migrations.RunPython(copy_repo)]
