# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20180314_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('commit', 'Commit'), ('tag', 'Tag'), ('org', 'Org Request'), ('qa', 'QA Testing')], max_length=8),
        ),
    ]
