# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0016_plan_test_dashboard"),
        ("plan", "0016_auto_20180904_1457"),
    ]

    operations = []
