# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-17 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20180912_2020'),
        ('plan', '0018_planrepository_active'),
    ]

    operations = [
    ]
