# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("plan", "0020_auto_20181018_1636")]

    operations = [
        migrations.AlterModelOptions(
            name="planrepository",
            options={
                "base_manager_name": "objects",
                "ordering": ["repo", "plan"],
                "permissions": (
                    ("run_plan", "Run Plan"),
                    ("view_builds", "View Builds"),
                    ("rebuild_builds", "Rebuild Builds"),
                    ("qa_builds", "QA Builds"),
                    ("org_login", "Login to Org"),
                ),
                "verbose_name_plural": "Plan Repositories",
            },
        )
    ]
