# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_migrate_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='public',
        ),
    ]
