# Generated by Django 2.1.3 on 2018-12-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0024_plan_role_and_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="role",
            field=models.CharField(
                choices=[
                    ("beta_release", "Beta Release"),
                    ("beta_test", "Beta Test"),
                    ("deploy", "Deployment"),
                    ("feature", "Feature Test"),
                    ("feature_robot", "Feature Test Robot"),
                    ("other", "Other"),
                    ("qa", "QA Org"),
                    ("release_deploy", "Release Deploy"),
                    ("release", "Release"),
                    ("release_test", "Release Test"),
                    ("scratch", "Scratch Org"),
                ],
                max_length=16,
            ),
        ),
    ]
