# Generated by Django 2.1.5 on 2019-01-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_remove_repository_public'),
        ('plan', '0025_auto_20181207_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRepositoryTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('commit', 'Commit'), ('tag', 'Tag')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('plan_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.PlanRepository')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Repository')),
            ],
        ),
    ]
