# Generated by Django 2.1.5 on 2019-02-07 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0025_auto_20181207_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRepositoryTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('source_plan_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sources', to='plan.PlanRepository')),
                ('target_plan_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Triggers', to='plan.PlanRepository')),
            ],
            options={
                'verbose_name_plural': 'Plan Repository Triggers',
                'ordering': ['target_plan_repo', 'source_plan_repo'],
                'permissions': (('run_plan', 'Run Plan'), ('view_builds', 'View Builds'), ('rebuild_builds', 'Rebuild Builds'), ('org_login', 'Login to Org')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='planrepositorytrigger',
            unique_together={('target_plan_repo', 'source_plan_repo')},
        ),
    ]
