# Generated by Django 2.1.7 on 2019-04-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("plan", "0026_auto_20190209_0101")]

    operations = [
        migrations.AlterModelOptions(
            name="planrepository",
            options={
                "base_manager_name": "objects",
                "ordering": ["repo", "plan"],
                "permissions": (
                    ("run_plan", "Run Plan"),
                    ("view_builds", "View Builds"),
                    ("rebuild_builds", "Rebuild Builds"),
                    ("qa_builds", "QA Builds"),
                    ("org_login", "Login to Org"),
                    ("view_stats", "View aggregate and individual method metrics"),
                ),
                "verbose_name_plural": "Plan Repositories",
            },
        )
    ]
