# Generated by Django 2.2 on 2019-05-15 02:49

from datetime import datetime, time, timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0027_planschedule"),
    ]

    operations = []
