# Generated by Django 2.2 on 2019-05-15 02:49

from django.db import migrations, models
from scheduler.models import RepeatableJob
from datetime import datetime, timezone, time


def install_periodic_builds_job(apps, schema_editor):
    midnight_utc = datetime.now(tz=timezone.utc).replace(hour=0, minute=0)
    job, created = RepeatableJob.objects.get_or_create(
        callable="metaci.plan.tasks.run_scheduled_hourly",
        enabled=True,
        name="hourly_builds_job",
        queue="short",
        defaults={
            "interval": 1,
            "interval_unit": "hours",
            "scheduled_time": midnight_utc,
        },
    )
    job, created = RepeatableJob.objects.get_or_create(
        callable="metaci.plan.tasks.run_scheduled_daily",
        enabled=True,
        name="daily_builds_job",
        queue="short",
        defaults={
            "interval": 24,
            "interval_unit": "hours",
            "scheduled_time": midnight_utc,
        },
    )


def uninstall_periodic_builds_job(apps, schema_editor):
    RepeatableJob.objects.filter(name="hourly_builds_job").delete()
    RepeatableJob.objects.filter(name="daily_builds_job").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0027_planschedule"),
        ("scheduler", "0005_added_result_ttl"),
    ]

    operations = [
        migrations.RunPython(
            install_periodic_builds_job, reverse_code=uninstall_periodic_builds_job
        )
    ]
