# Generated by Django 2.2.5 on 2019-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("plan", "0030_plan_priority")]

    operations = [
        migrations.RemoveField(model_name="plan", name="priority"),
        migrations.AddField(
            model_name="plan",
            name="queue",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("medium", "medium priority"),
                    ("high", "high priority"),
                ],
                default="default",
                max_length=16,
            ),
        ),
    ]
