# Generated by Django 2.2.9 on 2020-01-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0032_set_plan_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="build_timeout",
            field=models.IntegerField(default=28800),
        ),
        migrations.AlterField(
            model_name="plan",
            name="queue",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("medium", "medium priority"),
                    ("high", "high priority"),
                    ("robot", "robot tests"),
                ],
                default="default",
                max_length=16,
            ),
        ),
    ]
