# Generated by Django 2.2.16 on 2020-09-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0033_auto_20200121_0110"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="commit_status_template",
            field=models.CharField(
                blank=True,
                help_text="Template for the commit message set after a successful build.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="context",
            field=models.CharField(
                blank=True,
                help_text="If set, builds of this plan will update the commit status in GitHub using this context.",
                max_length=255,
                null=True,
            ),
        ),
    ]
