# Generated by Django 2.2.16 on 2020-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0034_auto_20200910_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("commit", "Commit"),
                    ("status", "Commit Status"),
                    ("tag", "Tag"),
                ],
                max_length=8,
            ),
        ),
    ]
