# Generated by Django 3.1.6 on 2021-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0036_auto_20210302_0149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="queue",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("medium", "medium priority"),
                    ("high", "high priority"),
                    ("robot", "robot tests"),
                    ("long-running", "long-running"),
                ],
                default="default",
                max_length=16,
            ),
        ),
    ]
