# Generated by Django 3.1.7 on 2021-03-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0037_auto_20210315_2204"),
        ("plan", "0037_auto_20210304_0908"),
    ]

    operations = []
