# Generated by Django 3.1.10 on 2021-06-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0038_merge_20210324_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="change_traffic_control",
            field=models.BooleanField(
                default=False,
                help_text="Default is set to False, set to true to toggle change traffic control integration on this plan.",
            ),
        ),
    ]
