# Generated by Django 3.1.13 on 2021-08-09 16:52

from django.db import migrations, models


def migrate_regexes(apps, schema_editor):
    Plan = apps.get_model("plan", "Plan")
    for plan in Plan.objects.filter(trigger="status").iterator():
        if plan.regex:
            # Migrate the regex to the new commit_status_regex field.

            plan.commit_status_regex = plan.regex
            plan.regex = None
            plan.save()


def migrate_regexes_reverse(apps, schema_editor):
    Plan = apps.get_model("plan", "Plan")
    for plan in Plan.objects.filter(trigger="status").iterator():
        if plan.commit_status_regex:
            plan.regex = plan.commit_status_regex
            plan.commit_status_regex = None
            plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0039_plan_change_traffic_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="commit_status_regex",
            field=models.CharField(
                blank=True,
                help_text="For Plans that use the trigger Commit Status, run builds when the commit status matches this regex.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_regexes, migrate_regexes_reverse),
    ]
