# Generated by Django 3.1.13 on 2021-11-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0041_auto_20211110_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrepository',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planrepos', to='plan.plan'),
        ),
    ]
