# Generated by Django 3.1.13 on 2021-11-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0042_auto_20211117_0113'),
        ('plan', '0041_auto_20211123_2247'),
    ]

    operations = [
    ]
