# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cumulusci", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ScratchOrgInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("org_id", models.CharField(max_length=32)),
                ("deleted", models.BooleanField(default=False)),
                ("json", models.TextField()),
                ("json_dx", models.TextField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_deleted", models.DateTimeField(blank=True, null=True)),
            ],
        )
    ]
