# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 14:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cumulusci", "0002_scratchorginstance")]

    operations = [
        migrations.RenameField(
            model_name="scratchorginstance", old_name="org_id", new_name="sf_org_id"
        ),
        migrations.AddField(
            model_name="scratchorginstance",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="cumulusci.Org",
            ),
            preserve_default=False,
        ),
    ]
