# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cumulusci', '0005_scratchorginstance_delete_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='last_deploy',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='last_deploy_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='org_type',
            field=models.CharField(choices=[(b'SCRATCH', b'Scratch Org Definition'), (b'PACKAGING', b'Packaging Org'), (b'UNMANAGED', b'Persistent Test Org (Unmanaged)'), (b'BETA', b'Persistent Test Org (Beta Package)'), (b'PRODUCTION', b'Persistent Test Org (Production Package)')], default=b'PRODUCTION', max_length=50),
        ),
        migrations.AddField(
            model_name='org',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org',
            name='release_cycle',
            field=models.CharField(blank=True, choices=[(b'QA', b'QA Orgs'), (b'SANDBOX', b'Sandboxes'), (b'PRODUCTION', b'Production and Developer Orgs')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='supertype',
            field=models.CharField(choices=[(b'CI', b'CI Test Org'), (b'REGISTERED', b'Registered Org')], default=b'CI', max_length=50),
        ),
    ]
