# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 22:02
from __future__ import unicode_literals

from django.db import migrations

from metaci.cumulusci.models import Org
from metaci.cumulusci import choices

def classify_orgs(apps, schema_editor):
    # use order of ops in place of logic...
    orgs = Org.objects.all()
    beta_orgs = orgs.filter(name__contains='beta')
    beta_orgs.update(org_type=choices.ORGTYPE_BETA)
    unmanaged_orgs = orgs.filter(name__contains='unmanaged')
    unmanaged_orgs.update(org_type=choices.ORGTYPE_UNMANAGED)
    packaging_orgs = orgs.filter(name__contains='packaging')
    packaging_orgs.update(org_type=choices.ORGTYPE_PACKAGING)
    scratch_orgs = orgs.filter(scratch=True)
    scratch_orgs.update(org_type=choices.ORGTYPE_SCRATCH)


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0006_auto_20171115_2156'),
    ]

    operations = [
        migrations.RunPython(classify_orgs),
    ]
