# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0006_remove_scratchorginstance_json_dx'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchorginstance',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
