# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-18 00:12
from __future__ import unicode_literals

from django.db import migrations
from metaci.cumulusci import choices

import logging

LOGGER = logging.getLogger(__name__)

def find_org_id(apps, schema_editor):
    Org = apps.get_model('cumulusci', 'Org')
    for org in Org.objects.all():
        if not org.scratch and org.json:
            token_id = json.loads(org.json)['id']
            org.sf_org_id = token_id.split('/')[-2]
            if len(org.sf_org_id) == 15 or len(org.sf_org_id) == 18:
                org.save()
                    
def classify_orgs(apps, schema_editor):
    Org = apps.get_model('cumulusci', 'Org')
    orgs = Org.objects.all()
    beta_orgs = orgs.filter(name__contains='beta')
    beta_orgs.update(org_type=choices.ORGTYPE_BETA)
    unmanaged_orgs = orgs.filter(name__contains='unmanaged')
    unmanaged_orgs.update(org_type=choices.ORGTYPE_UNMANAGED)
    packaging_orgs = orgs.filter(name__contains='packaging')
    packaging_orgs.update(org_type=choices.ORGTYPE_PACKAGING)
    scratch_orgs = orgs.filter(scratch=True)
    scratch_orgs.update(org_type=choices.ORGTYPE_SCRATCH)


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0006_org_orgmartfields'),
    ]

    operations = [
        migrations.RunPython(find_org_id),
        migrations.RunPython(classify_orgs),
    ]
