# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0007_auto_setorgtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='last_deploy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
