# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 22:32
from __future__ import unicode_literals

import json

from django.db import migrations, models
from metaci.cumulusci.models import Org

def find_org_id(apps, schema_editor):
    #this isn't fast
    for org in Org.objects.all():
        if not org.scratch and org.json:
            token_id = json.loads(org.json)['id']
            org_id = token_id.split('/')[-2]
            if len(org_id) == 15 or len(org_id) == 18:
                print('updating org {} with {}' .format(org, org.org_id))
                org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0008_auto_20171115_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='org_id',
            field=models.CharField(blank=True, max_length=18, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(find_org_id)
    ]
