# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0008_org_management_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='management_group',
        ),
    ]
