# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import metaci.cumulusci.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cumulusci', '0008_org_drop_scratch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAdminAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_message', models.TextField()),
                ('action_flag', models.CharField(choices=[('lock', 'lock'), ('unlock', 'unlock'), ('run', 'run'), ('login', 'login'), ('other', 'other')], default='other', max_length=20)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('related_object_object_id', models.TextField(blank=True, null=True)),
                ('related_object_object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to='cumulusci.Org')),
                ('related_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', metaci.cumulusci.models.AdminEntryManager()),
            ],
        ),
    ]
