# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0009_orgadminaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['name', 'repo__owner', 'repo__name'], 'permissions': (('manage_locks', 'manage locks'), ('run_builds', 'run builds'), ('login', 'login'))},
        ),
    ]
