# Generated by Django 2.2.4 on 2019-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cumulusci", "0009_remove_org_management_group")]

    operations = [
        migrations.AddField(
            model_name="scratchorginstance",
            name="org_note",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        )
    ]
