# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0009_org_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
