# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0009_org_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='last_deploy',
        ),
        migrations.RemoveField(
            model_name='org',
            name='last_deploy_version',
        ),
        migrations.RemoveField(
            model_name='org',
            name='release_cycle',
        ),
        migrations.RemoveField(
            model_name='org',
            name='scratch',
        ),
        migrations.AddField(
            model_name='org',
            name='push_schedule',
            field=models.CharField(blank=True, choices=[(b'QA', b'QA Orgs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_type',
            field=models.CharField(choices=[(b'SCRATCH', b'Scratch Org Definition'), (b'PACKAGING', b'Packaging Org'), (b'UNMANAGED', b'Persistent Test Org (Unmanaged)'), (b'BETA', b'Persistent Test Org (Beta Package)'), (b'PRODUCTION', b'Persistent Test Org (Production Package)'), (b'TRIAL', b'Trial Source Org (Production Package'), (b'ADMIN', b'Administrative Org (no package)')], default=b'PRODUCTION', max_length=50),
        ),
    ]
