# Generated by Django 2.2.11 on 2020-05-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0010_scratchorginstance_org_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorginstance",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="cumulusci.Org",
            ),
        ),
    ]
