# Generated by Django 3.1.7 on 2021-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0011_auto_20200505_1940"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="configuration_item",
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                help_text="Set when integrating with an external system for change traffic control.",
            ),
        ),
    ]
