# Generated by Django 3.1.7 on 2021-03-24 21:04

import json

from django.db import migrations, models
from django.db.migrations.operations.special import RunPython
from django.utils.translation import gettext_lazy as _

import metaci.fields

# @@@ we may need to limit scratch org instances to those created in the past 30 days to perform the migration reasonably quickly


def encrypt_data(apps, schema_editor):
    # copy JSON data from TextField to EncryptedJSONField
    for model_name in ("Org", "ScratchOrgInstance", "Service"):
        model = apps.get_model("cumulusci", model_name)
        for record in model.objects.iterator():
            record.json_e = json.loads(record.json)
            record.save()


def decrypt_data(apps, schema_editor):
    # copy JSON data from EncryptedJSONField to TextField
    for model_name in ("Org", "ScratchOrgInstance", "Service"):
        model = apps.get_model("cumulusci", model_name)
        for record in model.objects.iterator():
            record.json = json.dumps(record.json_e)
            record.save()


def remove_social_tokens(apps, schema_editor):
    # we aren't using oauth tokens except for authentication, so we don't need to store them
    SocialToken = apps.get_model("socialaccount", "SocialToken")
    SocialToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0011_auto_20200505_1940"),
    ]

    operations = [
        # add encrypted fields (null)
        migrations.AddField(
            model_name="org",
            name="json_e",
            field=metaci.fields.EncryptedJSONField(null=True),
        ),
        migrations.AddField(
            model_name="scratchorginstance",
            name="json_e",
            field=metaci.fields.EncryptedJSONField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="json_e",
            field=metaci.fields.EncryptedJSONField(null=True),
        ),
        # make plaintext fields nullable so that we can run the migration backwards
        migrations.AlterField(
            model_name="org", name="json", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="scratchorginstance",
            name="json",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="service", name="json", field=models.TextField(null=True)
        ),
        # copy data
        migrations.RunPython(encrypt_data, decrypt_data),
        # remove plaintext fields
        migrations.RemoveField(model_name="org", name="json"),
        migrations.RemoveField(model_name="scratchorginstance", name="json"),
        migrations.RemoveField(model_name="service", name="json"),
        # rename encrypted fields
        migrations.RenameField(model_name="org", old_name="json_e", new_name="json"),
        migrations.RenameField(
            model_name="scratchorginstance", old_name="json_e", new_name="json"
        ),
        migrations.RenameField(
            model_name="service", old_name="json_e", new_name="json"
        ),
        # make encrypted fields non-nullable
        migrations.AlterField(
            model_name="org", name="json", field=metaci.fields.EncryptedJSONField()
        ),
        migrations.AlterField(
            model_name="scratchorginstance",
            name="json",
            field=metaci.fields.EncryptedJSONField(),
        ),
        migrations.AlterField(
            model_name="service", name="json", field=metaci.fields.EncryptedJSONField()
        ),
        # remove social tokens (we aren't using them)
        migrations.RunPython(remove_social_tokens),
    ]
