# Generated by Django 3.1.7 on 2021-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0012_org_configuration_item"),
    ]

    operations = []
