# Generated by Django 3.1.7 on 2021-03-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0012_encrypt_secrets"),
        ("cumulusci", "0013_auto_20210316_1652"),
    ]

    operations = []
