# Generated by Django 3.1.7 on 2021-04-02 20:41

import django.core.serializers.json
from django.db import migrations

import metaci.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0014_merge_20210326_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="json",
            field=metaci.fields.EncryptedJSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="scratchorginstance",
            name="json",
            field=metaci.fields.EncryptedJSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="json",
            field=metaci.fields.EncryptedJSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
