# Generated by Django 3.1.13 on 2021-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0016_metapool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgpool',
            name='dependencies',
            field=models.JSONField(default=dict),
        ),
    ]
