# Generated by Django 3.1.13 on 2021-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cumulusci", "0017_auto_20211208_1840"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgpool",
            name="dependencies",
        ),
        migrations.AddField(
            model_name="orgpool",
            name="frozen_steps",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="orgpool",
            name="cache_key",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
