# Generated by Django 3.1.13 on 2021-12-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0041_auto_20211208_1840'),
        ('cumulusci', '0019_auto_20211208_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgpool',
            name='commit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='orgpool',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_pools', to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='orgpool',
            name='cache_key',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='orgpool',
            name='frozen_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='orgpool',
            name='org_shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_pools', to='cumulusci.org'),
        ),
    ]
