# Generated by Django 3.1.13 on 2021-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumulusci', '0021_auto_20211210_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgpool',
            name='frozen_steps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
