# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('json', models.TextField()),
                ('scratch', models.BooleanField(default=False)),
            ],
        ),
    ]
