# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('commit', 'Commit'), ('tag', 'Tag'), ('pr', 'Pull Request')], max_length=8)),
                ('regex', models.CharField(blank=True, max_length=255, null=True)),
                ('build_pr_commits', models.BooleanField(default=False)),
                ('flows', models.CharField(max_length=255)),
                ('org', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255)),
            ],
        ),
    ]
