# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
        ('trigger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='repo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='github.Repository'),
            preserve_default=False,
        ),
    ]
