# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_trigger_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='github.Repository'),
        ),
    ]
