# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0004_auto_20161213_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
