# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0005_trigger_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
