# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0006_auto_20170106_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
