# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0007_trigger_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'ordering': ['name', 'repo__owner', 'repo__name', 'active', 'context']},
        ),
    ]
