SUPERTYPE_REGISTERED = 'REGISTERED'
SUPERTYPE_CI = 'CI'
SUPERTYPE_CHOICES = (
    (SUPERTYPE_CI,'CI Test Org'),
    (SUPERTYPE_REGISTERED, 'Registered Org')
)

ORGTYPE_SCRATCH = 'SCRATCH'
ORGTYPE_PACKAGING = 'PACKAGING'
ORGTYPE_UNMANAGED = 'UNMANAGED'
ORGTYPE_BETA = 'BETA'
ORGTYPE_PRODUCTION = 'PRODUCTION'

ORGTYPE_CHOICES = (
    (ORGTYPE_SCRATCH, 'Scratch Org Definition'),
    (ORGTYPE_PACKAGING, 'Packaging Org'),
    (ORGTYPE_UNMANAGED, 'Persistent Test Org (Unmanaged)'),
    (ORGTYPE_BETA, 'Persistent Test Org (Beta Package)'),
    (ORGTYPE_PRODUCTION, 'Persistent Test Org (Production Package)'),
)

RELEASE_QA = 'QA'
RELEASE_SANDBOX = 'SANDBOX'
RELEASE_PRODUCTION = 'PRODUCTION'

RELEASE_CHOICES = (
    (RELEASE_QA, 'QA Orgs'),
    (RELEASE_SANDBOX, 'Sandboxes'),
    (RELEASE_PRODUCTION, 'Production and Developer Orgs')
)